#!/bin/bash

#SBATCH --gres=gpumem:30g
#SBATCH --ntasks=4
#SBATCH --mem-per-cpu=10000
#SBATCH --gpus-per-node=4
#SBATCH --time=4:00:00
#SBATCH -o output_log_test


module load stack/2024-06 gcc/12.2.0 openmpi/4.1.6

mpiexec -np 4 python3 /cluster/project/krause/yunkao/echo_from_noise/semantic_diffusion_model/image_sample.py \
 --datadir /cluster/project/krause/yunkao/echo_from_noise/data_preparation/CAMUS_augmented_data/2CH_ED_augmented \
 --resume_checkpoint /cluster/project/krause/yunkao/echo_from_noise/output/model040000.pt \
 --results_dir /cluster/project/krause/yunkao/echo_from_noise/results_2CH_ED  \
 --num_samples 2250 --is_train False --inference_on_train True
